// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: triggers/run-completion-event-trigger/proto/run_completion_event_trigger.proto

package run_completion_event_trigger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_SUCCEEDED Status = 0
	Status_FAILED    Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "SUCCEEDED",
		1: "FAILED",
	}
	Status_value = map[string]int32{
		"SUCCEEDED": 0,
		"FAILED":    1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDescGZIP(), []int{0}
}

type RunCompletionEvent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PipelineName         string                 `protobuf:"bytes,1,opt,name=pipeline_name,json=pipelineName,proto3" json:"pipeline_name,omitempty"`
	Provider             string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	RunConfigurationName string                 `protobuf:"bytes,3,opt,name=run_configuration_name,json=runConfigurationName,proto3" json:"run_configuration_name,omitempty"`
	RunId                string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	RunName              string                 `protobuf:"bytes,5,opt,name=run_name,json=runName,proto3" json:"run_name,omitempty"`
	Status               Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=run_completion_event_trigger.Status" json:"status,omitempty"`
	Artifacts            []*Artifact            `protobuf:"bytes,7,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	RunStartTime         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=run_start_time,json=runStartTime,proto3" json:"run_start_time,omitempty"`
	RunEndTime           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=run_end_time,json=runEndTime,proto3" json:"run_end_time,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RunCompletionEvent) Reset() {
	*x = RunCompletionEvent{}
	mi := &file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCompletionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCompletionEvent) ProtoMessage() {}

func (x *RunCompletionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCompletionEvent.ProtoReflect.Descriptor instead.
func (*RunCompletionEvent) Descriptor() ([]byte, []int) {
	return file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *RunCompletionEvent) GetPipelineName() string {
	if x != nil {
		return x.PipelineName
	}
	return ""
}

func (x *RunCompletionEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RunCompletionEvent) GetRunConfigurationName() string {
	if x != nil {
		return x.RunConfigurationName
	}
	return ""
}

func (x *RunCompletionEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunCompletionEvent) GetRunName() string {
	if x != nil {
		return x.RunName
	}
	return ""
}

func (x *RunCompletionEvent) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_SUCCEEDED
}

func (x *RunCompletionEvent) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *RunCompletionEvent) GetRunStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RunStartTime
	}
	return nil
}

func (x *RunCompletionEvent) GetRunEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RunEndTime
	}
	return nil
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDescGZIP(), []int{1}
}

func (x *Artifact) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto protoreflect.FileDescriptor

const file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDesc = "" +
	"\n" +
	"Ntriggers/run-completion-event-trigger/proto/run_completion_event_trigger.proto\x12\x1crun_completion_event_trigger\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x03\n" +
	"\x12RunCompletionEvent\x12#\n" +
	"\rpipeline_name\x18\x01 \x01(\tR\fpipelineName\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x124\n" +
	"\x16run_configuration_name\x18\x03 \x01(\tR\x14runConfigurationName\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x19\n" +
	"\brun_name\x18\x05 \x01(\tR\arunName\x12<\n" +
	"\x06status\x18\x06 \x01(\x0e2$.run_completion_event_trigger.StatusR\x06status\x12D\n" +
	"\tartifacts\x18\a \x03(\v2&.run_completion_event_trigger.ArtifactR\tartifacts\x12@\n" +
	"\x0erun_start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\frunStartTime\x12<\n" +
	"\frun_end_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"runEndTime\":\n" +
	"\bArtifact\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name*#\n" +
	"\x06Status\x12\r\n" +
	"\tSUCCEEDED\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x012{\n" +
	"\x19RunCompletionEventTrigger\x12^\n" +
	"\x10ProcessEventFeed\x120.run_completion_event_trigger.RunCompletionEvent\x1a\x16.google.protobuf.Empty\"\x00B\x87\x01Z\x84\x01github.com/sky-uk/kfp-operator/triggers/run-completion-event-trigger/proto/run-completion-event-trigger;run_completion_event_triggerb\x06proto3"

var (
	file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDescOnce sync.Once
	file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDescData []byte
)

func file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDescGZIP() []byte {
	file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDescOnce.Do(func() {
		file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDesc), len(file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDesc)))
	})
	return file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDescData
}

var file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_goTypes = []any{
	(Status)(0),                   // 0: run_completion_event_trigger.Status
	(*RunCompletionEvent)(nil),    // 1: run_completion_event_trigger.RunCompletionEvent
	(*Artifact)(nil),              // 2: run_completion_event_trigger.Artifact
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_depIdxs = []int32{
	0, // 0: run_completion_event_trigger.RunCompletionEvent.status:type_name -> run_completion_event_trigger.Status
	2, // 1: run_completion_event_trigger.RunCompletionEvent.artifacts:type_name -> run_completion_event_trigger.Artifact
	3, // 2: run_completion_event_trigger.RunCompletionEvent.run_start_time:type_name -> google.protobuf.Timestamp
	3, // 3: run_completion_event_trigger.RunCompletionEvent.run_end_time:type_name -> google.protobuf.Timestamp
	1, // 4: run_completion_event_trigger.RunCompletionEventTrigger.ProcessEventFeed:input_type -> run_completion_event_trigger.RunCompletionEvent
	4, // 5: run_completion_event_trigger.RunCompletionEventTrigger.ProcessEventFeed:output_type -> google.protobuf.Empty
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() {
	file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_init()
}
func file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_init() {
	if File_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDesc), len(file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_goTypes,
		DependencyIndexes: file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_depIdxs,
		EnumInfos:         file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_enumTypes,
		MessageInfos:      file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_msgTypes,
	}.Build()
	File_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto = out.File
	file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_goTypes = nil
	file_triggers_run_completion_event_trigger_proto_run_completion_event_trigger_proto_depIdxs = nil
}
