{{- if .Values.statusFeedback.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kfp-operator.fullname" . }}-run-completion-event-trigger
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: run-completion-event-trigger
  ports:
  - protocol: TCP
    port: {{ .Values.runcompletionEventTrigger.server.port }}
    targetPort: grpc-server
{{- end -}}
