apiVersion: v1
kind: Secret
metadata:
  name: argo-artifacts-minio
  namespace: argo
type: Opaque
stringData:
  accesskey: minioadmin
  secretkey: minioadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        command: ["minio", "server", "/data"]
        env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: argo
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-artifacts-minio
  namespace: kfp-operator-system
type: Opaque
stringData:
  accesskey: minioadmin
  secretkey: minioadmin
