apiVersion: pipelines.kubeflow.org/v1beta1
kind: RunConfiguration
metadata:
  name: stub-runconfiguration
  namespace: default
spec:
  run:
    provider: kfp-operator-system/stub
    pipeline: stub-pipeline
    experimentName: Default
  triggers:
    onChange:
    - pipeline
    schedules:
    - cronExpression: "0 * * * *"
      startTime: "2025-01-01T00:00:00Z"
      endTime: "2030-12-31T23:59:59Z"
