namespace:
  create: false
fullnameOverride: kfp-operator
logging:
  verbosity: info
manager:
  multiversion:
    enabled: true
  webhookCertificates:
    provider: cert-manager
  argo:
    serviceAccount:
      name: kfp-operator-argo
      create: true
  configuration:
    defaultProvider: kfp
    defaultExperiment: Default
    runCompletionTTL: 30s
  monitoring:
    create: false
  runcompletionWebhook:
    port: 8082
    endpoints:
    - host: kfp-operator-run-completion-event-trigger.kfp-operator-system
      path: ""
      port: 50051

runcompletionEventTrigger:
  enabled: true
  replicas: 1
  nats:
    subject: events
    server:
      port: 4222
  server:
    port: 50051

statusFeedback:
  enabled: true

providers:
  - kfp
  - vai

provider:
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/gcloud/key-file.json
  volumes:
    - name: gcp-credentials
      secret:
        secretName: gcp-credentials
  volumeMounts:
    - name: gcp-credentials
      mountPath: /etc/gcloud
      readOnly: true
