{{- range $providerName, $providerBlock := .Values.providers -}}
{{- $labels := include "kfp-operator.eventsourceServer.labels" (merge (dict "ProviderName" $providerName) $ ) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kfp-operator.fullname" $ }}-{{ $providerName }}-eventsource-server
  namespace: {{ include "kfp-operator.argoNamespace" $ }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- $labels | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- (deepCopy $.Values.eventing.eventsourceServer.metadata | merge (dict "labels" ($labels | fromYaml))) | toYaml | nindent 6 }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: eventsource-server
          command:
          - /provider
          args:
          - --provider-config
          - /provider-config.yaml
          - eventsource-server
          - --port=50051
          image: {{ include "kfp-operator.providerImage" (merge (dict "Provider" $providerBlock) $ ) }}
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            {{- $.Values.eventing.eventsourceServer.resources | toYaml | nindent 12 }}
          ports:
          - name: grpc
            containerPort: 50051
            protocol: TCP
          volumeMounts:
          - mountPath: /provider-config.yaml
            name: provider-configs
            subPath: {{ $providerName }}
      volumes:
      - name: provider-configs
        configMap:
          name: {{ include "kfp-operator.fullname" $ }}-providers
      serviceAccountName: {{ $providerBlock.serviceAccount.name }}
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kfp-operator.fullname" $ }}-{{ $providerName }}-eventsource-server
  namespace: {{ include "kfp-operator.argoNamespace" $ }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  selector:
    {{- $labels | nindent 4 }}
  ports:
    - name: grpc
      port: {{ $.Values.eventing.eventsourceServer.port }}
      protocol: TCP
      targetPort: grpc
{{ end }}
