{{- if .Values.statusFeedback.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ include "kfp-operator.fullname" . }}-events-webhook
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  service:
    ports:
      - port: {{ .Values.statusFeedback.webhook.port }}
        targetPort: {{ .Values.statusFeedback.webhook.port }}
  webhook:
    run-completion-event-source:
      port: "{{ .Values.statusFeedback.webhook.port }}"
      endpoint: "{{ .Values.statusFeedback.webhook.endpoint }}"
      method: POST
{{- end -}}
