{{- if .Values.statusFeedback.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kfp-operator.fullname" . }}-status-updater
  namespace: {{ include "kfp-operator.argoNamespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kfp-operator.fullname" . }}-status-updater-submitter
  namespace: {{ include "kfp-operator.argoNamespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kfp-operator.fullname" . }}-status-updater
rules:
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - runs
  verbs:
  - get
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - runs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - runconfigurations
  verbs:
  - get
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - runconfigurations/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kfp-operator.fullname" . }}-workflow-submitter
  namespace: {{ include "kfp-operator.argoNamespace" . }}
rules:
  - apiGroups:
    - argoproj.io
    resources:
    - workflowtemplates
    verbs:
    - get
  - apiGroups:
    - argoproj.io
    resources:
    - workflows
    verbs:
    - create
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kfp-operator.fullname" . }}-status-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kfp-operator.fullname" . }}-status-updater
subjects:
- kind: ServiceAccount
  name: {{ include "kfp-operator.fullname" . }}-status-updater
  namespace: {{ include "kfp-operator.argoNamespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kfp-operator.fullname" . }}-status-updater
  namespace: {{ include "kfp-operator.argoNamespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kfp-operator.fullname" . }}-workflow-executor
subjects:
- kind: ServiceAccount
  name: {{ include "kfp-operator.fullname" . }}-status-updater
  namespace: {{ include "kfp-operator.argoNamespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kfp-operator.fullname" . }}-status-updater-submitter
  namespace: {{ include "kfp-operator.argoNamespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kfp-operator.fullname" . }}-workflow-submitter
subjects:
  - kind: ServiceAccount
    name: {{ include "kfp-operator.fullname" . }}-status-updater-submitter
    namespace: {{ include "kfp-operator.argoNamespace" . }}
{{- end }}
