{{- if gt (len .Values.providers) 0 }}
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-complete-run
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  serviceAccountName: {{ include "kfp-operator.fullname" . }}-status-updater
  ttlStrategy:
    {{- .Values.manager.argo.ttlStrategy | toYaml | nindent 4 }}
  entrypoint: complete-run
  templates:
  - name: complete-run
    metadata:
      {{- $.Values.manager.argo.metadata | toYaml | nindent 10 }}
    retryStrategy: {}
    inputs:
      artifacts:
      - name: run-completion-event
        path: /run-completion-event.json
        raw:
          data: |
            {{`{{workflow.parameters.run-completion-event}}`}}
    script:
    container:
      image: {{ include "kfp-operator.trimmedContainerRegistry" . }}kfp-operator-status-updater:{{ .Chart.AppVersion }}
      command:
      - /status-updater
      args:
      - --run-completion-event
      - /run-completion-event.json
      - complete-run
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ include "kfp-operator.fullname" $ }}-events
  namespace: {{ include "kfp-operator.argoNamespace" $ }}
spec:
  nats:
    {{ include "kfp-operator.fullname" $ }}-events:
      connectionBackoff:
        duration: 10s
        factor: 2
        jitter: 0.2
        steps: 5
      jsonBody: true
      subject: events
      url: nats://eventbus-{{ include "kfp-operator.fullname" . }}-events-stan-svc.{{ include "kfp-operator.argoNamespace" . }}.svc:4222
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ include "kfp-operator.fullname" $ }}-status-updater
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  template:
    serviceAccountName: {{ include "kfp-operator.fullname" . }}-status-updater-submitter
    metadata:
      {{- $.Values.manager.argo.metadata | toYaml | nindent 6 }}
  dependencies:
  - eventName: {{ include "kfp-operator.fullname" $ }}-events
    eventSourceName: {{ include "kfp-operator.fullname" $ }}-events
    name: events
  triggers:
  - template:
      name: complete-run
      argoWorkflow:
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: {{ include "kfp-operator.fullname" $ }}-complete-run-
            spec:
              arguments:
                parameters:
                - name: run-completion-event
                  value: "set below"
              workflowTemplateRef:
                name: {{ include "kfp-operator.fullname" $ }}-complete-run
        parameters:
        - src:
            dependencyName: events
            dataKey: body.data
          dest: spec.arguments.parameters.0.value
{{- end }}
