{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  {{- $defaultMetadata := dict "labels"  ((include "kfp-operator.labels" .) | fromYaml) -}}
  {{- (merge .Values.namespace.metadata $defaultMetadata) | toYaml | nindent 2 }}
{{- end -}}
