{{- if .Values.global.manager.multiversion.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kfp-operator.fullname" . }}-webhook-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.manager.webhookServicePort }}
  selector:
    control-plane: controller-manager
{{- end }}
