---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    {{- if eq .Values.manager.webhookCertificates.provider "cert-manager" }}
    cert-manager.io/inject-ca-from: {{ .Values.namespace.name }}/{{ include "kfp-operator.fullname" . }}-serving-cert
    {{- end }}
  name: {{ include "kfp-operator.fullname" . }}-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kfp-operator.fullname" . }}-webhook-service
        namespace: {{ .Values.namespace.name }}
        path: /validate-pipelines-kubeflow-org-v1beta1-pipeline
      {{- if eq .Values.manager.webhookCertificates.provider "custom" }}
      caBundle: {{ .Values.manager.webhookCertificates.caBundle }}
      {{- end }}
    failurePolicy: Fail
    name: vpipeline.kb.io
    rules:
      - apiGroups:
          - pipelines.kubeflow.org
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pipelines
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kfp-operator.fullname" . }}-webhook-service
        namespace: {{ .Values.namespace.name }}
        path: /validate-providers-kubeflow-org-v1beta1-provider
      {{- if eq .Values.manager.webhookCertificates.provider "custom" }}
      caBundle: {{ .Values.manager.webhookCertificates.caBundle }}
      {{- end }}
    failurePolicy: Fail
    name: vprovider.kb.io
    rules:
      - apiGroups:
          - providers.kubeflow.org
        apiVersions:
          - v1beta1
        operations:
          - UPDATE
          - DELETE
        resources:
          - providers
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kfp-operator.fullname" . }}-webhook-service
        namespace: {{ .Values.namespace.name }}
        path: /validate-pipelines-kubeflow-org-v1beta1-run
      {{- if eq .Values.manager.webhookCertificates.provider "custom" }}
      caBundle: {{ .Values.manager.webhookCertificates.caBundle }}
      {{- end }}
    failurePolicy: Fail
    name: vrun.kb.io
    rules:
      - apiGroups:
          - pipelines.kubeflow.org
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - runs
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kfp-operator.fullname" . }}-webhook-service
        namespace: {{ .Values.namespace.name }}
        path: /validate-pipelines-kubeflow-org-v1beta1-runconfiguration
      {{- if eq .Values.manager.webhookCertificates.provider "custom" }}
      caBundle: {{ .Values.manager.webhookCertificates.caBundle }}
      {{- end }}
    failurePolicy: Fail
    name: vrunconfiguration.kb.io
    rules:
      - apiGroups:
          - pipelines.kubeflow.org
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - runconfigurations
    sideEffects: None
