
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ include "kfp-operator.fullname" . }}-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kfp-operator.fullname" . }}-webhook-service
        namespace: {{ .Values.namespace.name }}-system
        path: /validate-pipelines-kubeflow-org-v1alpha4-run
    failurePolicy: Fail
    name: vrun.kb.io
    rules:
      - apiGroups:
          - pipelines.kubeflow.org
        apiVersions:
          - v1alpha4
        operations:
          - CREATE
          - UPDATE
        resources:
          - runs
    sideEffects: None
