{{- $providerName := .Values.provider.name }}
{{- $labels := include "kfp-operator-provider.eventsourceServer.labels" $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kfp-operator-provider.resource-prefix" $ }}-{{ $providerName }}-eventsource-server
  namespace: {{ include "kfp-operator-provider.namespace" $ }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- $labels | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- (deepCopy $.Values.eventsourceServer.metadata | merge (dict "labels" ($labels | fromYaml))) | toYaml | nindent 6 }}
    spec:
      serviceAccountName: {{ .Values.eventsourceServer.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: eventsource-server
          command:
          - /provider
          args:
          - --provider
          - {{ .Values.provider.name }}
          - eventsource-server
          - --port=50051
          image: {{ include "kfp-operator-provider.image" $ }}
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            {{- $.Values.eventsourceServer.resources | toYaml | nindent 12 }}
          ports:
          - name: grpc
            containerPort: 50051
            protocol: TCP
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kfp-operator-provider.resource-prefix" $ }}-{{ $providerName }}-eventsource-server
  namespace: {{ include "kfp-operator-provider.namespace" $ }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  selector:
    {{- $labels | nindent 4 }}
  ports:
    - name: grpc
      port: {{ $.Values.eventsourceServer.port }}
      protocol: TCP
      targetPort: grpc
