apiVersion: pipelines.kubeflow.org/v1beta1
kind: Pipeline
metadata:
  name: penguin-pipeline-training
spec:
  provider: provider-namespace/kfp
  image: kfp-quickstart-base:v1
  framework:
    type: tfx
    parameters:
      pipeline: penguin_training.pipeline.create_components
