apiVersion: pipelines.kubeflow.org/v1beta1
kind: RunConfiguration
metadata:
    name: penguin-pipeline-recurring-run
spec:
    run:
      provider: provider-namespace/kfp
      pipeline: penguin-pipeline
      experimentName: penguin-experiment
      parameters:
      - name: push_destination
        value: 'gs://my-bucket/penguin-pipeline'
    triggers:
      schedules:
      - cronExpression: 0 * * * *
        startTime: 2024-01-01T00:00:00Z
        endTime: 2024-12-31T23:59:59Z
