# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: "gomod"
  directories:
  - "/"
  - "/docs-gen"
  schedule:
    interval: "weekly"
  rebase-strategy: "disabled"
  allow:
  - dependency-type: "direct"
  commit-message:
    prefix: "chore(deps)"
  open-pull-requests-limit: 3

- package-ecosystem: "uv"
  directories:
  - "/compilers/**"
  - "/docs-gen/includes/master/**"
  schedule:
    interval: "weekly"
  rebase-strategy: "disabled"
  allow:
  - dependency-type: "direct"
  commit-message:
    prefix: "chore(deps)"
  exclude-paths:
  - "docs-gen/includes/versions/**"
  open-pull-requests-limit: 3

- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  rebase-strategy: "disabled"
  commit-message:
    prefix: "chore(deps)"
  exclude-paths:
  - "docs-gen/includes/versions/**"
  open-pull-requests-limit: 0
