# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: "gomod"
  directories:
  - "/"
  - "/docs-gen"
  schedule:
    interval: "weekly"
  rebase-strategy: "disabled"
  allow:
  - dependency-type: "direct"
  commit-message:
    prefix: "chore(deps)"
  open-pull-requests-limit: 10
  groups:
    go-minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
    go-major:
      applies-to: version-updates
      update-types:
      - "major"
    go-security-minor-and-patch:
      applies-to: security-updates
      update-types:
      - "minor"
      - "patch"
    go-security-major:
      applies-to: security-updates
      update-types:
      - "major"

# TFX modules
# setuptools version 82 removed pkg_resources which breaks TFX
# setuptools version 83 requires Python 3.10+, and compilers/tfx only support 3.9
- package-ecosystem: "uv"
  directories:
  - "/compilers/tfx"
  - "/compilers/tfx/integration/**"
  - "/docs-gen/includes/master/quickstart"
  - "/docs-gen/includes/master/quickstart-with-dependencies/**"
  schedule:
    interval: "weekly"
  rebase-strategy: "disabled"
  allow:
  - dependency-type: "direct"
  commit-message:
    prefix: "chore(deps)"
  exclude-paths:
  - "docs-gen/includes/versions/**"
  ignore:
  - dependency-name: "setuptools"
    versions: [">=82"]
  open-pull-requests-limit: 10
  groups:
    uv-minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
    uv-major:
      applies-to: version-updates
      update-types:
      - "major"
    uv-security-minor-and-patch:
      applies-to: security-updates
      update-types:
      - "minor"
      - "patch"
    uv-security-major:
      applies-to: security-updates
      update-types:
      - "major"

# kfp-sdk modules
# setuptools version below 83 to support Python 3.9
- package-ecosystem: "uv"
  directories:
  - "/compilers/kfp-sdk"
  - "/docs-gen/includes/master/kfpsdk-quickstart"
  schedule:
    interval: "weekly"
  rebase-strategy: "disabled"
  allow:
  - dependency-type: "direct"
  commit-message:
    prefix: "chore(deps)"
  exclude-paths:
  - "docs-gen/includes/versions/**"
  ignore:
  - dependency-name: "setuptools"
    versions: [">=83"]
  open-pull-requests-limit: 10
  groups:
    uv-minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
    uv-major:
      applies-to: version-updates
      update-types:
      - "major"
    uv-security-minor-and-patch:
      applies-to: security-updates
      update-types:
      - "minor"
      - "patch"
    uv-security-major:
      applies-to: security-updates
      update-types:
      - "major"

- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  rebase-strategy: "disabled"
  commit-message:
    prefix: "chore(deps)"
  exclude-paths:
  - "docs-gen/includes/versions/**"
  open-pull-requests-limit: 0
