# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
    - "/"
    - "/docs-gen"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    allow:
    - dependency-type: "direct"

  - package-ecosystem: "poetry"
    directory: "/docs-gen/includes/master/kfpsdk-quickstart"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    allow:
    - dependency-type: "direct"

  - package-ecosystem: "poetry"
    directory: "/docs-gen/includes/0.7.0/kfpsdk-quickstart"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    allow:
    - dependency-type: "direct"
