{{- if and .Values.eventsourceServer.create .Values.eventsourceServer.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "kfp-operator.fullname" . }}-eventsource-server-role
rules:
- apiGroups:
    - argoproj.io
  resources:
    - workflows
  verbs:
    - get
    - list
    - patch
    - update
    - watch
{{- end -}}
