# Default values for provider.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

containerRegistry: "ghcr.io/kfp-operator"

namespace:
  create: true
  name: kfp-operator-system
  metadata: {}

kfpOperator:
  fullname: kfp-operator

provider:
  name: kfp
  type: kfp
  executionMode: v1
  serviceAccount:
    name: kfp-operator-kfp
    create: true
  configuration:
    kfpNamespace: kubeflow
    restKfpApiUrl: http://ml-pipeline.kubeflow:8888
    grpcMetadataStoreAddress: metadata-grpc-service.kubeflow-pipelines:8080
    grpcKfpApiAddress: ml-pipeline.kubeflow-pipelines:8887

logging:
  verbosity: # info

eventsourceServer:
  serviceAccount:
    name: kfp-operator-kfp
  create: false
  metadata: {}
  port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 200Mi
