# Default values for provider.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

containerRegistry: "ghcr.io/provider"

namespace:
  create: true
  name: "kfp-operator-system"
  metadata: {}

provider: {}

logging:
  verbosity: # info

eventsourceServer:
  create: false
  metadata: {}
  port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 200Mi
