apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kfp-operator.name" . }}-manager-config
  namespace: {{ .Values.controller.namespace }}
data:
  controller_manager_config.yaml: |-
    apiVersion: config.kubeflow.org/v1
    kind: KfpControllerConfig
    controller:
      health:
        healthProbeBindAddress: :8081
      metrics:
        bindAddress: :8080
      webhook:
        port: 9443
      leaderElection:
        leaderElect: false
        resourceName: kfp-operator-lock
    spec:
      imagePullPolicy: {{ .Values.argo.imagePullPolicy }}
      compilerImage: {{ .Values.containerRegistry }}/kfp-operator-argo-compiler:{{ .Chart.AppVersion }}
      kfpSdkImage: {{ .Values.containerRegistry }}/kfp-operator-argo-kfp-sdk:{{ .Chart.AppVersion }}
      kfpEndpoint: {{ .Values.argo.kfpEndpoint }}
      serviceAccount: {{ .Values.argo.serviceAccount }}
      pipelineStorage: {{ .Values.argo.pipelineStorage }}
      defaultBeamArgs:
        project: {{ .Values.argo.dataflowProject }}
