{{- if (include "kfp-operator.providerTypeExists" (merge (dict "ProviderType" "vai") . )) -}}
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  nats:
    native:
      containerTemplate:
        resources:
          requests:
            cpu: 100m
      metadata:
        {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 8 }}
      metricsContainerTemplate:
        resources:
          requests:
            cpu: 100m
{{- end -}}
