{{- if and .Values.manager.rbac.create .Values.manager.monitoring.create .Values.manager.monitoring.rbacSecured -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kfp-operator.fullname" . }}-metrics-reader
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
{{- end -}}
