---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-kubeflow-org-v1beta1-pipeline
  failurePolicy: Fail
  name: vpipeline.kb.io
  rules:
  - apiGroups:
    - pipelines.kubeflow.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-kubeflow-org-v1beta1-run
  failurePolicy: Fail
  name: vrun.kb.io
  rules:
  - apiGroups:
    - pipelines.kubeflow.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-kubeflow-org-v1beta1-runconfiguration
  failurePolicy: Fail
  name: vrunconfiguration.kb.io
  rules:
  - apiGroups:
    - pipelines.kubeflow.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runconfigurations
  sideEffects: None
