[project]
name = "tfx_compiler"
version = "0.0.0" # set by poetry-dynamic-versioning
description = ""
authors = []
requires-python = ">=3.9"

dependencies = [
    "click>=7,<8",
    "PyYAML>=5.4.1",
    "kfp==1.8.22"
]

[project.scripts]
tfx_compiler = 'tfx_compiler.__main__:main'

[dependency-groups]
dev = [
    "pytest>=7.4.0",
    "tfx==1.14",
    "shapely<2"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["tfx_compiler"]