apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: common-steps
  namespace: kfp-operator-system
spec:
  templates:
  - name: select-provider-parameter
    inputs:
      parameters:
      - name: parameter
    script:
      volumeMounts:
      - name: providers-config
        mountPath: /providers-config
      command:
      - ash
      image: mikefarah/yq:4.27.5
      source: yq e '.{{inputs.parameters.parameter}}' '/providers-config/{{workflow.parameters.provider-name}}'
  - name: select-resource-image
    inputs:
      artifacts:
      - name: resource-definition
        path: /resource-definition.yaml
        raw:
          data: |
            {{workflow.parameters.resource-definition}}
    script:
      command:
      - ash
      image: mikefarah/yq:4.27.5
      source: yq e '.image' /resource-definition.yaml
  - name: delete
    inputs:
      parameters:
      - name: provider-image
      - name: provider-sa
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    podSpecPatch: '{"serviceAccountName": "{{inputs.parameters.provider-sa}}"}'
    metadata: {}
    container:
      image: "{{inputs.parameters.provider-image}}"
      volumeMounts:
      - name: providers-config
        mountPath: /providers-config
      command:
      - /provider
      args:
      - --provider-config
      - /providers-config/{{workflow.parameters.provider-name}}
      - '{{workflow.parameters.resource-kind}}'
      - delete
      - --{{workflow.parameters.resource-kind}}-id
      - '{{workflow.parameters.resource-id}}'
      - --out
      - /tmp/provider-output.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: delete
  namespace: kfp-operator-system
spec:
  volumes:
  - name: providers-config
    configMap:
      name: kfp-operator-providers
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterFailure: 3600
    secondsAfterSuccess: 600
  arguments:
    parameters:
    - name: provider-name
    - name: resource-kind
    - name: resource-id
  entrypoint: main
  serviceAccountName: kfp-operator-argo
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{steps.provider.outputs.parameters.provider-output}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: select-provider-sa
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: serviceAccount
    - - name: provider
        templateRef:
          name: kfp-operator-common-steps
          template: delete
        arguments:
          parameters:
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
          - name: provider-sa
            value: '{{steps.select-provider-sa.outputs.result}}'
