apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: common-steps
  namespace: kfp-operator-system
spec:
  templates:
  - name: select-provider-parameter
    inputs:
      parameters:
      - name: parameter
      artifacts:
      - name: provider-config
        path: /provider-config.yaml
        raw:
          data: |
            {{workflow.parameters.provider-config}}
    script:
      command:
      - ash
      image: mikefarah/yq:4.27.5
      source: yq e '.{{inputs.parameters.parameter}}' /provider-config.yaml
  - name: select-pipeline-image
    inputs:
      artifacts:
      - name: pipeline-definition
        path: /pipeline-definition.yaml
        raw:
          data: |
            {{workflow.parameters.pipeline-definition}}
    script:
      command:
      - ash
      image: mikefarah/yq:4.27.5
      source: yq e '.image' /pipeline-definition.yaml
