apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: experiment-steps
spec:
  templates:
  - name: create
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: experiment-definition
        path: /tmp/experiment-definition.yaml
        raw:
          data: |
            {{workflow.parameters.experiment-definition}}
      - name: provider-config
        path: /tmp/provider-config.yaml
        raw:
          data: |
            {{workflow.parameters.provider-config}}
    outputs:
      parameters:
      - name: experiment-id
        valueFrom:
          path: /tmp/id.txt
    metadata: {}
    container:
      image: "{{inputs.parameters.provider-image}}"
      command:
      - /provider
      args:
      - experiment
      - create
      - --experiment-definition
      - /tmp/experiment-definition.yaml
      - --provider-config
      - /tmp/provider-config.yaml
      - --out
      - /tmp/id.txt
  - name: update
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: experiment-definition
        path: /tmp/experiment-definition.yaml
        raw:
          data: |
            {{workflow.parameters.experiment-definition}}
      - name: provider-config
        path: /tmp/provider-config.yaml
        raw:
          data: |
            {{workflow.parameters.provider-config}}
    outputs:
      parameters:
      - name: experiment-id
        valueFrom:
          path: /tmp/id.txt
    metadata: {}
    container:
      image: "{{inputs.parameters.provider-image}}"
      command:
      - /provider
      args:
      - experiment
      - update
      - --experiment-definition
      - /tmp/experiment-definition.yaml
      - --provider-config
      - /tmp/provider-config.yaml
      - --experiment-id
      - '{{workflow.parameters.experiment-id}}'
      - --out
      - /tmp/id.txt
  - name: delete
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: provider-config
        path: /tmp/provider-config.yaml
        raw:
          data: |
            {{workflow.parameters.provider-config}}
    metadata: {}
    container:
      image: "{{inputs.parameters.provider-image}}"
      command:
      - /provider
      args:
      - experiment
      - delete
      - --experiment-definition
      - /tmp/experiment-definition.yaml
      - --provider-config
      - /tmp/provider-config.yaml
      - --experiment-id
      - '{{workflow.parameters.experiment-id}}'
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: create-experiment
spec:
  arguments:
    parameters:
    - name: experiment-definition
    - name: provider-config
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: experiment-id
        valueFrom:
          parameter: '{{steps.create.outputs.parameters.experiment-id}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-image
          clusterScope: true
    - - name: create
        arguments:
          parameters:
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
        templateRef:
          name: kfp-operator-experiment-steps
          template: create
          clusterScope: true
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: update-experiment
spec:
  arguments:
    parameters:
      - name: experiment-definition
      - name: provider-config
      - name: experiment-id
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: experiment-id
        valueFrom:
          parameter: '{{steps.update.outputs.parameters.experiment-id}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-image
          clusterScope: true
    - - name: update
        arguments:
          parameters:
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
        templateRef:
          name: kfp-operator-experiment-steps
          template: update
          clusterScope: true
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: delete-experiment
spec:
  arguments:
    parameters:
    - name: provider-config
    - name: experiment-id
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-image
          clusterScope: true
    - - name: delete
        arguments:
          parameters:
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
        templateRef:
          name: kfp-operator-experiment-steps
          template: delete
          clusterScope: true
