apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pipeline-steps
  namespace: kfp-operator-system
spec:
  volumes:
    - name: providers-config
      configMap:
        name: kfp-operator-providers
  templates:
    - name: compile
      inputs:
        parameters:
        - name: pipeline-image
        - name: execution-mode
        artifacts:
        - name: pipeline-definition
          raw:
            data: |
              {{workflow.parameters.pipeline-definition}}
          path: /pipeline-definition.yaml
      outputs:
        artifacts:
        - name: pipeline
          path: /pipeline.yaml
      metadata: {}
      container:
        name: pipeline
        image: '{{inputs.parameters.pipeline-image}}'
        volumeMounts:
        - mountPath: /shared
          name: shared
        command:
        - /shared/compile.sh
        args:
        - --output_file
        - /pipeline.yaml
        - --pipeline_config
        - /pipeline-definition.yaml
        - --execution_mode
        - "{{inputs.parameters.execution-mode}}"
      volumes:
      - name: shared
      initContainers:
      - args:
        - /shared
        image: kfp-operator-argo-kfp-compiler:latest
        mirrorVolumeMounts: true
        name: compile
    - name: create
      inputs:
        parameters:
        - name: provider-image
        artifacts:
        - name: pipeline
          path: /pipeline.yaml
        - name: pipeline-definition
          path: /pipeline-definition.yaml
          raw:
            data: |
              {{workflow.parameters.pipeline-definition}}
      outputs:
        parameters:
        - name: provider-output
          valueFrom:
            path: /provider-output.yaml
      metadata: {}
      container:
        image: "{{inputs.parameters.provider-image}}"
        volumeMounts:
        - name: providers-config
          mountPath: /providers-config
        command:
        - /provider
        args:
        - --provider-config
        - /providers-config/{{workflow.parameters.provider-name}}
        - pipeline
        - create
        - --pipeline-definition
        - /pipeline-definition.yaml
        - --pipeline-file
        - /pipeline.yaml
        - --out
        - /provider-output.yaml
    - name: update
      inputs:
        artifacts:
        - name: pipeline
          path: /pipeline.yaml
        - name: pipeline-definition
          path: /pipeline-definition.yaml
          raw:
            data: |
              {{workflow.parameters.pipeline-definition}}
        parameters:
        - name: pipeline-id
        - name: provider-image
      outputs:
        parameters:
        - name: provider-output
          valueFrom:
            path: /provider-output.yaml
      metadata: {}
      container:
        image: "{{inputs.parameters.provider-image}}"
        volumeMounts:
        - name: providers-config
          mountPath: /providers-config
        command:
        - /provider
        args:
        - --provider-config
        - /providers-config/{{workflow.parameters.provider-name}}
        - pipeline
        - update
        - --pipeline-definition
        - /pipeline-definition.yaml
        - --pipeline-id
        - '{{inputs.parameters.pipeline-id}}'
        - --pipeline-file
        - /pipeline.yaml
        - --out
        - /provider-output.yaml
    - name: delete
      inputs:
        parameters:
        - name: provider-image
      outputs:
        parameters:
        - name: provider-output
          valueFrom:
            path: /provider-output.yaml
      metadata: {}
      container:
        image: "{{inputs.parameters.provider-image}}"
        volumeMounts:
        - name: providers-config
          mountPath: /providers-config
        command:
          - /provider
        args:
        - --provider-config
        - /providers-config/{{workflow.parameters.provider-name}}
        - pipeline
        - delete
        - --pipeline-definition
        - /pipeline-definition.yaml
        - --pipeline-id
        - '{{workflow.parameters.pipeline-id}}'
        - --out
        - /provider-output.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-pipeline
  namespace: kfp-operator-system
spec:
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterSuccess: 600
    secondsAfterFailure: 3600
  arguments:
    parameters:
    - name: provider-name
    - name: pipeline-definition
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{steps.provider.outputs.parameters.provider-output}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: select-execution-mode
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: executionMode
    - - name: select-pipeline-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-pipeline-image
    - - name: compile
        templateRef:
          name: kfp-operator-pipeline-steps
          template: compile
        arguments:
          parameters:
          - name: pipeline-image
            value: "{{steps.select-pipeline-image.outputs.result}}"
          - name: execution-mode
            value: "{{steps.select-execution-mode.outputs.result}}"
    - - name: provider
        templateRef:
          name: kfp-operator-pipeline-steps
          template: create
        arguments:
          artifacts:
          - from: '{{steps.compile.outputs.artifacts.pipeline}}'
            name: pipeline
          parameters:
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: update-pipeline
  namespace: kfp-operator-system
spec:
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterSuccess: 600
    secondsAfterFailure: 3600
  arguments:
    parameters:
    - name: provider-name
    - name: pipeline-id
    - name: pipeline-definition
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{steps.provider.outputs.parameters.provider-output}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: select-execution-mode
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: executionMode
    - - name: select-pipeline-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-pipeline-image
    - - name: compile
        templateRef:
          name: kfp-operator-pipeline-steps
          template: compile
        arguments:
          parameters:
          - name: pipeline-image
            value: "{{steps.select-pipeline-image.outputs.result}}"
          - name: execution-mode
            value: "{{steps.select-execution-mode.outputs.result}}"
    - - name: provider
        templateRef:
          name: kfp-operator-pipeline-steps
          template: update
        arguments:
          artifacts:
          - from: '{{steps.compile.outputs.artifacts.pipeline}}'
            name: pipeline
          parameters:
          - name: pipeline-id
            value: '{{workflow.parameters.pipeline-id}}'
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: delete-pipeline
  namespace: kfp-operator-system
spec:
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterSuccess: 600
    secondsAfterFailure: 3600
  arguments:
    parameters:
    - name: provider-name
    - name: pipeline-id
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{steps.provider.outputs.parameters.provider-output}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: provider
        templateRef:
          name: kfp-operator-pipeline-steps
          template: delete
        arguments:
          parameters:
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
