apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: runconfiguration-steps
spec:
  templates:
  - name: create
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: runconfiguration-definition
        path: /tmp/runconfiguration-definition.yaml
        raw:
          data: |
            {{workflow.parameters.runconfiguration-definition}}
      - name: provider-config
        path: /tmp/provider-config.yaml
        raw:
          data: |
            {{workflow.parameters.provider-config}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    metadata: {}
    container:
      image: "{{inputs.parameters.provider-image}}"
      command:
      - /provider
      args:
      - runconfiguration
      - create
      - --runconfiguration-definition
      - /tmp/runconfiguration-definition.yaml
      - --provider-config
      - /tmp/provider-config.yaml
      - --out
      - /tmp/provider-output.yaml
  - name: update
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: runconfiguration-definition
        path: /tmp/runconfiguration-definition.yaml
        raw:
          data: |
            {{workflow.parameters.runconfiguration-definition}}
      - name: provider-config
        path: /tmp/provider-config.yaml
        raw:
          data: |
            {{workflow.parameters.provider-config}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    metadata: {}
    container:
      image: "{{inputs.parameters.provider-image}}"
      command:
      - /provider
      args:
      - runconfiguration
      - update
      - --runconfiguration-definition
      - /tmp/runconfiguration-definition.yaml
      - --provider-config
      - /tmp/provider-config.yaml
      - --runconfiguration-id
      - '{{workflow.parameters.runconfiguration-id}}'
      - --out
      - /tmp/provider-output.yaml
  - name: delete
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: provider-config
        path: /tmp/provider-config.yaml
        raw:
          data: |
            {{workflow.parameters.provider-config}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    metadata: {}
    container:
      image: "{{inputs.parameters.provider-image}}"
      command:
      - /provider
      args:
      - runconfiguration
      - delete
      - --runconfiguration-definition
      - /tmp/runconfiguration-definition.yaml
      - --provider-config
      - /tmp/provider-config.yaml
      - --runconfiguration-id
      - '{{workflow.parameters.runconfiguration-id}}'
      - --out
      - /tmp/provider-output.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: create-runconfiguration
spec:
  arguments:
    parameters:
    - name: runconfiguration-definition
    - name: provider-config
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{steps.provider.outputs.parameters.provider-output}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-image
          clusterScope: true
    - - name: provider
        arguments:
          parameters:
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
        templateRef:
          name: kfp-operator-runconfiguration-steps
          template: create
          clusterScope: true
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: update-runconfiguration
spec:
  arguments:
    parameters:
    - name: runconfiguration-definition
    - name: provider-config
    - name: runconfiguration-id
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{steps.provider.outputs.parameters.provider-output}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-image
          clusterScope: true
    - - name: provider
        arguments:
          parameters:
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
        templateRef:
          name: kfp-operator-runconfiguration-steps
          template: update
          clusterScope: true
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: delete-runconfiguration
spec:
  arguments:
    parameters:
    - name: provider-config
    - name: runconfiguration-id
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{steps.provider.outputs.parameters.provider-output}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-image
          clusterScope: true
    - - name: provider
        arguments:
          parameters:
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
        templateRef:
          name: kfp-operator-runconfiguration-steps
          template: delete
          clusterScope: true
