apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: runconfiguration-steps
  namespace: kfp-operator-system
spec:
  templates:
  - name: create
    inputs:
      parameters:
      - name: provider-image
      - name: provider-sa
      artifacts:
      - name: runconfiguration-definition
        path: /runconfiguration-definition.yaml
        raw:
          data: |
            {{workflow.parameters.runconfiguration-definition}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    podSpecPatch: '{"serviceAccountName": "{{inputs.parameters.provider-sa}}"}'
    metadata: {}
    container:
      image: "{{inputs.parameters.provider-image}}"
      volumeMounts:
      - name: providers-config
        mountPath: /providers-config
      command:
      - /provider
      args:
      - --provider-config
      - /providers-config/{{workflow.parameters.provider-name}}
      - runconfiguration
      - create
      - --runconfiguration-definition
      - /runconfiguration-definition.yaml
      - --out
      - /tmp/provider-output.yaml
  - name: update
    inputs:
      parameters:
      - name: provider-image
      - name: provider-sa
      artifacts:
      - name: runconfiguration-definition
        path: /runconfiguration-definition.yaml
        raw:
          data: |
            {{workflow.parameters.runconfiguration-definition}}
    podSpecPatch: '{"serviceAccountName": "{{inputs.parameters.provider-sa}}"}'
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    metadata: {}
    container:
      image: "{{inputs.parameters.provider-image}}"
      volumeMounts:
      - name: providers-config
        mountPath: /providers-config
      command:
      - /provider
      args:
      - --provider-config
      - /providers-config/{{workflow.parameters.provider-name}}
      - runconfiguration
      - update
      - --runconfiguration-definition
      - /runconfiguration-definition.yaml
      - --runconfiguration-id
      - '{{workflow.parameters.runconfiguration-id}}'
      - --out
      - /tmp/provider-output.yaml
  - name: delete
    inputs:
      parameters:
      - name: provider-image
      - name: provider-sa
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    podSpecPatch: '{"serviceAccountName": "{{inputs.parameters.provider-sa}}"}'
    metadata: {}
    container:
      image: "{{inputs.parameters.provider-image}}"
      volumeMounts:
      - name: providers-config
        mountPath: /providers-config
      command:
      - /provider
      args:
      - --provider-config
      - /providers-config/{{workflow.parameters.provider-name}}
      - runconfiguration
      - delete
      - --runconfiguration-definition
      - /runconfiguration-definition.yaml
      - --runconfiguration-id
      - '{{workflow.parameters.runconfiguration-id}}'
      - --out
      - /tmp/provider-output.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-runconfiguration
  namespace: kfp-operator-system
spec:
  serviceAccountName: kfp-operator-workflow-runner
  volumes:
  - name: providers-config
    configMap:
      name: kfp-operator-providers
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterSuccess: 600
    secondsAfterFailure: 3600
  arguments:
    parameters:
    - name: provider-name
    - name: runconfiguration-definition
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{steps.provider.outputs.parameters.provider-output}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: select-provider-sa
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: serviceAccount
    - - name: provider
        templateRef:
          name: kfp-operator-runconfiguration-steps
          template: create
        arguments:
          parameters:
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
          - name: provider-sa
            value: '{{steps.select-provider-sa.outputs.result}}'
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: update-runconfiguration
  namespace: kfp-operator-system
spec:
  serviceAccountName: kfp-operator-workflow-runner
  volumes:
  - name: providers-config
    configMap:
      name: kfp-operator-providers
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterSuccess: 600
    secondsAfterFailure: 3600
  arguments:
    parameters:
    - name: provider-name
    - name: runconfiguration-id
    - name: runconfiguration-definition
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{steps.provider.outputs.parameters.provider-output}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: select-provider-sa
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: serviceAccount
    - - name: provider
        templateRef:
          name: kfp-operator-runconfiguration-steps
          template: update
        arguments:
          parameters:
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
          - name: provider-sa
            value: '{{steps.select-provider-sa.outputs.result}}'
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: delete-runconfiguration
  namespace: kfp-operator-system
spec:
  serviceAccountName: kfp-operator-workflow-runner
  volumes:
  - name: providers-config
    configMap:
      name: kfp-operator-providers
  ttlStrategy:
    secondsAfterCompletion: 600
    secondsAfterSuccess: 600
    secondsAfterFailure: 3600
  arguments:
    parameters:
    - name: provider-name
    - name: runconfiguration-id
  entrypoint: main
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{steps.provider.outputs.parameters.provider-output}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: select-provider-sa
        templateRef:
          name: kfp-operator-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: serviceAccount
    - - name: provider
        templateRef:
          name: kfp-operator-runconfiguration-steps
          template: delete
        arguments:
          parameters:
          - name: provider-image
            value: '{{steps.select-provider-image.outputs.result}}'
          - name: provider-sa
            value: '{{steps.select-provider-sa.outputs.result}}'
