# permissions for end users to view pipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-viewer-role
rules:
- apiGroups:
  - pipelines.kubeflow.org.my.domain
  resources:
  - pipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipelines.kubeflow.org.my.domain
  resources:
  - pipelines/status
  verbs:
  - get
