# permissions for end users to edit kfpcontrollerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectconfig-editor-role
rules:
- apiGroups:
  - config.kubeflow.org
  resources:
  - kfpcontrollerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.kubeflow.org
  resources:
  - kfpcontrollerconfigs/status
  verbs:
  - get
