# permissions for end users to view runconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: run-viewer-role
rules:
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - runs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - runs/status
  verbs:
  - get
