{{- $providerName := .Values.provider.name }}
{{- $labels := include "kfp-operator-provider.service.labels" $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kfp-operator-provider.resource-prefix" $ }}-{{ $providerName }}-service
  namespace: {{ include "kfp-operator-provider.namespace" $ }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- $labels | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- (deepCopy $.Values.service.metadata | merge (dict "labels" ($labels | fromYaml))) | toYaml | nindent 6 }}
    spec:
      serviceAccountName: {{ .Values.service.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
      containers:
      - name: provider-service
        image: {{ include "kfp-operator-provider-service.image" $ }}
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          {{- $.Values.service.resources | toYaml | nindent 10 }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
          - name: config
            mountPath: /etc/provider-service/config.yaml
            subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: {{ $providerName }}-{{ include "kfp-operator-provider.resource-prefix" . }}-service-config
