# Originally from https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start/base/cluster-workflow-template-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-clusterrole-binding
subjects:
  - kind: ServiceAccount
    name: argo
    namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: argo-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: argo-role
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - clusterworkflowtemplates
      - workflowtemplates
    verbs:
      - get
      - list
      - watch
