apiVersion: pipelines.kubeflow.org/v1alpha5
kind: RunConfiguration
metadata:
    name: penguin-pipeline-recurring-run
spec:
    run:
      pipeline: penguin-pipeline
      experimentName: penguin-experiment
    triggers:
    - type: schedule
      cronExpression: '0 * * * *'
