apiVersion: pipelines.kubeflow.org/v1alpha6
kind: RunConfiguration
metadata:
    name: penguin-pipeline-recurring-run
spec:
    run:
      pipeline: penguin-pipeline
      experimentName: penguin-experiment
    triggers:
      schedules:
      - cronExpression: 0 * * * *
        startTime: 2024-01-01T00:00:00Z
        endTime: 2024-12-31T23:59:59Z
