apiVersion: pipelines.kubeflow.org/v1alpha1
kind: RunConfiguration
metadata:
    name: penguin-pipeline-recurring-run
spec:
    pipelineName: penguin-pipeline
    experimentName: penguin-experiment
    schedule: '0 0 * * * *'
