fullnameOverride: kfp-operator
manager:
  argo:
    serviceAccount: pipeline-runner
  configuration:
    defaultExperiment: Default
    pipelineStorage: {STORAGE_LOCATION}
  provider:
    type: kfp
    configuration:
      restKfpApiUrl: http://ml-pipeline.kubeflow:8888
# Uncomment below for eventing-support
#     grpcKfpApiAddress: ml-pipeline.kubeflow:8887
#     grpcMetadataStoreAddress: metadata-grpc-service.kubeflow:8080
#eventsourceServer:
#  create: true
