fullnameOverride: kfp-operator
manager:
  argo:
    serviceAccount: pipeline-runner
  configuration:
    defaultExperiment: Default
    pipelineStorage: {STORAGE_LOCATION}
  provider:
    type: kfp
    configuration:
      endpoint: http://ml-pipeline.kubeflow:8888
# Uncomment below for eventing-support
#eventsourceServer:
#  create: true
#  mlmdUrl: metadata-grpc-service.kubeflow:8080
#  kfpUrl: ml-pipeline.kubeflow:8887
