[tool.poetry]
name = "penguin_examples"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "3.10.12"
tfx = "1.15.1"
shapely = "<2"
kfp = "2.0.0"
setuptools = "~=70.0"
