apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native: {}
---
apiVersion: argoproj.io/v1alpha1
  kind: EventSource
  metadata:
    name: model-update-eventsource
  spec:
    generic:
      example:
        insecure: true
        url: "kfp-operator-model-update-eventsource-server.kfp-operator-system.svc:50051"
        config: |-
          kfpNamespace: kubeflow-pipelines
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: model-update-sensor
spec:
  template:
    serviceAccountName: events-sa
  dependencies:
    - name: model-update-eventsource
      eventSourceName: model-update-eventsource
      eventName: model-update
      filters:
        data:
          - path: body.payload.pipelineName
            type: string
            comparator: "="
            value:
              - "penguin-pipeline" # Replace with the name of your pipeline
  triggers:
    - template:
        k8s:
          operation: apply
          source:
            resource:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: serving-config
              data:
                servingModel: ""
      parameters:
        - src:
            dependencyName: model-update-eventsource
            dataKey: "body.payload.servingModelArtifacts[0]"
          dest: data.servingModel
