apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: model-update-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: events-sa
  dependencies:
    - name: model-update-eventsource
      eventSourceName: model-update-eventsource
      eventName: model-update
  triggers:
    - template:
        # TODO: update configmap
        name: log-trigger
        log: {}
