apiVersion: pipelines.kubeflow.org/v1
kind: Pipeline
metadata:
  name: pipeline-sample
spec:
  image: us.gcr.io/ml-dev-uswe2/mlops/nbcu-us-metadata-enhancement:latest
  tfxComponents: main.pipelines.base_pipeline.create_components

