{{- if and .Values.provider.create .Values.provider.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kfp-provider-workflows.providerServiceAccountName" . }}
  namespace: {{ include "kfp-provider-workflows.namespace" . }}
{{- with .Values.provider.serviceAccount.metadata }}
  {{ . | toYaml | nindent 2 }}
{{- end }}
{{- end }}
