{{- if and .Values.manager.rbac.create (eq .Values.manager.provider.type "vai") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kfp-operator.fullname" . }}-vai-provider
  namespace: {{ .Values.namespace.name }}
rules:
- apiGroups:
    - argoproj.io
  resources:
    - workflows
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kfp-operator.fullname" . }}-vai-provider
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kfp-operator.fullname" . }}-vai-provider
subjects:
- kind: ServiceAccount
  name: {{ .Values.manager.provider.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
{{- end -}}
