{{ $found := false }}
{{- range $providerName, $providerBlock := .Values.providers -}}
  {{- if eq $providerBlock.type "vai" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kfp-operator.fullname" $ }}-vai-provider
  namespace: {{ $.Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kfp-operator.fullname" $ }}-vai-provider
subjects:
  - kind: ServiceAccount
    name: {{ $providerBlock.serviceAccount.name }}
    namespace: {{ $.Values.namespace.name }}
---
    {{ $found = true }}
  {{- end -}}
{{- end -}}
{{- if $found -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kfp-operator.fullname" $ }}-vai-provider
  namespace: {{ .Values.namespace.name }}
rules:
- apiGroups:
    - argoproj.io
  resources:
    - workflows
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
{{- end -}}
