{{- if eq .Values.manager.provider.type "vai" -}}
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ include "kfp-operator.fullname" . }}-run-enqueuer
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kfp-operator.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- $defaultMetadata := dict "labels"  ((include "kfp-operator.labels" .) | fromYaml) -}}
      {{- (merge .Values.manager.metadata $defaultMetadata) | toYaml | nindent 6 }}
    serviceAccountName: {{ .Values.manager.provider.serviceAccount.name }}
  pubSub:
    run-intents:
      jsonBody: true
      projectID: {{ .Values.manager.provider.configuration.vaiProject }}
      subscriptionID: {{ .Values.manager.provider.configuration.enqueuerRunIntentsSubscription }}
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ include "kfp-operator.fullname" . }}-run-enqueuer
  namespace: {{ .Values.namespace.name }}
spec:
  template:
    serviceAccountName: {{ .Values.manager.provider.serviceAccount.name }}
    metadata:
      {{- $defaultMetadata := dict "labels"  ((include "kfp-operator.labels" .) | fromYaml) -}}
      {{- (merge .Values.manager.metadata $defaultMetadata) | toYaml | nindent 6 }}
  dependencies:
    - name: run-intents
      eventSourceName: {{ include "kfp-operator.fullname" . }}-run-enqueuer
      eventName: run-intents
  triggers:
  - template:
      name: enqueue-run
      k8s:
        operation: create
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: {{ include "kfp-operator.fullname" . }}-enqueue-run-
            spec:
              ttlStrategy:
                secondsAfterCompletion: 300
              serviceAccountName: {{ .Values.manager.provider.serviceAccount.name }}
              entrypoint: enqueue
              arguments:
                parameters:
                - name: run-intent
                  value: "set from parameters block below"
              templates:
              - name: enqueue
                metadata:
                  {{- $defaultMetadata := dict "labels"  ((include "kfp-operator.labels" .) | fromYaml) -}}
                  {{- (merge .Values.manager.metadata $defaultMetadata) | toYaml | nindent 18 }}
                inputs:
                  artifacts:
                  - name: provider-config
                    path: /tmp/provider-config.yaml
                    raw:
                      data: |
                        {{- .Values.manager.provider.configuration | toYaml | nindent 24 }}
                  - name: run-intent
                    path: /tmp/run-intent.json
                    raw:
                      data: |
                        {{`{{workflow.parameters.run-intent}}`}}
                container:
                  image: {{ include "kfp-operator.providerImage" . }}
                  command:
                  - /provider
                  args:
                  - --provider-config
                  - /tmp/provider-config.yaml
                  - custom
                  - vai-run
                  - enqueue
                  - --run-intent
                  - /tmp/run-intent.json
        parameters:
          - src:
              dependencyName: run-intents
              dataKey: body
            dest: spec.arguments.parameters.0.value
{{- end -}}
