apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-compiled-workflow-steps
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  templates:
  - name: compile
    inputs:
      parameters:
      - name: resource-image
      - name: provider-config
      artifacts:
      - name: resource-definition
        raw:
          data: |
            {{`{{workflow.parameters.resource-definition}}`}}
        path: /resource-definition.yaml
      - name: provider-config
        path: /provider-config.json
        raw:
          data: |
            {{`{{workflow.parameters.provider-config}}`}}
    outputs:
      artifacts:
      - name: resource
        path: /tmp/resource.yaml
    metadata:
      {{- .Values.manager.argo.metadata | toYaml | nindent 6 }}
    activeDeadlineSeconds: {{ .Values.manager.argo.stepTimeoutSeconds.compile }}
    container:
      command:
      - /shared/compile.sh
      image: "{{`{{inputs.parameters.resource-image}}`}}"
      name: resource
      volumeMounts:
      - mountPath: /shared
        name: shared
      args:
      - --output_file
      - /tmp/resource.yaml
      - --{{`{{workflow.parameters.resource-kind}}`}}_config
      - /resource-definition.yaml
      - --provider_config
      - /providers-config.json
      {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
    volumes:
    - name: shared
    initContainers:
    - args:
      - /shared
      image: {{ include "kfp-operator.compilerImage" . }}
      mirrorVolumeMounts: true
      name: compile
      {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
  - name: create
    inputs:
      parameters:
      - name: provider-image
      - name: provider-sa
      - name: provider-config
      artifacts:
      - name: provider-config
        path: /provider-config.json
        raw:
          data: |
            {{`{{workflow.parameters.provider-config}}`}}
      - name: resource
        path: /resource.yaml
      - name: resource-definition
        path: /resource-definition.yaml
        raw:
          data: |
            {{`{{workflow.parameters.resource-definition}}`}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    podSpecPatch: '{"serviceAccountName": "{{`{{inputs.parameters.provider-sa}}`}}"}'
    metadata:
      {{- .Values.manager.argo.metadata | toYaml | nindent 6 }}
    activeDeadlineSeconds: {{ .Values.manager.argo.stepTimeoutSeconds.default }}
    container:
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      command:
      - /provider
      args:
      - --provider-config
      - /provider-config.json
      - '{{`{{workflow.parameters.resource-kind}}`}}'
      - create
      - --{{`{{workflow.parameters.resource-kind}}`}}-definition
      - /resource-definition.yaml
      - --{{`{{workflow.parameters.resource-kind}}`}}-file
      - /resource.yaml
      - --out
      - /tmp/provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
  - name: update
    inputs:
      artifacts:
      - name: provider-config
        path: /provider-config.json
        raw:
          data: |
            {{`{{workflow.parameters.provider-config}}`}}
      - name: resource
        path: /resource.yaml
      - name: resource-definition
        path: /resource-definition.yaml
        raw:
          data: |
            {{`{{workflow.parameters.resource-definition}}`}}
      parameters:
      - name: resource-id
      - name: provider-image
      - name: provider-sa
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    podSpecPatch: '{"serviceAccountName": "{{`{{inputs.parameters.provider-sa}}`}}"}'
    metadata:
      {{- .Values.manager.argo.metadata | toYaml | nindent 6 }}
    activeDeadlineSeconds: {{ .Values.manager.argo.stepTimeoutSeconds.default }}
    container:
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      command:
      - /provider
      args:
      - --provider-config
      - /provider-config.json
      - '{{`{{workflow.parameters.resource-kind}}`}}'
      - update
      - --{{`{{workflow.parameters.resource-kind}}`}}-definition
      - /resource-definition.yaml
      - --{{`{{workflow.parameters.resource-kind}}`}}-id
      - '{{`{{inputs.parameters.resource-id}}`}}'
      - --{{`{{workflow.parameters.resource-kind}}`}}-file
      - /resource.yaml
      - --out
      - /tmp/provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-create-compiled
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  ttlStrategy:
    {{- .Values.manager.argo.ttlStrategy | toYaml | nindent 4 }}
  arguments:
    parameters:
    - name: provider-config
    - name: resource-kind
    - name: resource-definition
  entrypoint: main
  serviceAccountName: {{ .Values.manager.argo.serviceAccount.name }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: field
            value: image
          - name: provider-config
            value: '{{`{{workflow.parameters.provider-config}}`}}'
    - - name: select-provider-sa
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: field
            value: serviceAccount
          - name: provider-config
            value: '{{`{{workflow.parameters.provider-config}}`}}'
    - - name: select-resource-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-resource-image
    - - name: compile
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-compiled-workflow-steps
          template: compile
        arguments:
          parameters:
          - name: resource-image
            value: '{{`{{steps.select-resource-image.outputs.result}}`}}'
    - - name: provider
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-compiled-workflow-steps
          template: create
        arguments:
          artifacts:
          - from: '{{`{{steps.compile.outputs.artifacts.resource}}`}}'
            name: resource
          parameters:
          - name: provider-image
            value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
          - name: provider-sa
            value: '{{`{{steps.select-provider-sa.outputs.result}}`}}'
          - name: provider-config
            value: '{{`{{workflow.parameters.provider-config}}`}}'
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-update-compiled
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  ttlStrategy:
    {{- .Values.manager.argo.ttlStrategy | toYaml | nindent 4 }}
  arguments:
    parameters:
    - name: provider-config
    - name: resource-kind
    - name: resource-id
    - name: resource-definition
  entrypoint: main
  serviceAccountName: {{ .Values.manager.argo.serviceAccount.name }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: field
            value: image
          - name: provider-config
            value: '{{`{{workflow.parameters.provider-config}}`}}'
    - - name: select-provider-sa
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: field
            value: serviceAccount
          - name: provider-config
            value: '{{`{{workflow.parameters.provider-config}}`}}'
    - - name: select-resource-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-resource-image
    - - name: compile
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-compiled-workflow-steps
          template: compile
        arguments:
          parameters:
          - name: resource-image
            value: '{{`{{steps.select-resource-image.outputs.result}}`}}'
          - name: provider-config
            value: '{{`{{workflow.parameters.provider-config}}`}}'
    - - name: provider
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-compiled-workflow-steps
          template: update
        arguments:
          artifacts:
          - from: '{{`{{steps.compile.outputs.artifacts.resource}}`}}'
            name: resource
          parameters:
          - name: resource-id
            value: '{{`{{workflow.parameters.resource-id}}`}}'
          - name: provider-image
            value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
          - name: provider-sa
            value: '{{`{{steps.select-provider-sa.outputs.result}}`}}'
          - name: provider-config
            value: '{{`{{workflow.parameters.provider-config}}`}}'
