apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-experiment-steps
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  volumes:
  - name: providers-config
    configMap:
      name: {{ include "kfp-operator.fullname" . }}-providers
  templates:
  - name: create
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: experiment-definition
        path: /experiment-definition.yaml
        raw:
          data: |
            {{`{{workflow.parameters.experiment-definition}}`}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /provider-output.yaml
    metadata:
      {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 6 }}
    container:
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      volumeMounts:
      - name: providers-config
        mountPath: /providers-config
      command:
      - /provider
      args:
      - --provider-config
      - /providers-config/{{`{{workflow.parameters.provider-name}}`}}
      - experiment
      - create
      - --experiment-definition
      - /experiment-definition.yaml
      - --out
      - /provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
  - name: update
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: experiment-definition
        path: /experiment-definition.yaml
        raw:
          data: |
            {{`{{workflow.parameters.experiment-definition}}`}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /provider-output.yaml
    metadata:
      {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 6 }}
    container:
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      volumeMounts:
      - name: providers-config
        mountPath: /providers-config
      command:
      - /provider
      args:
      - --provider-config
      - /providers-config/{{`{{workflow.parameters.provider-name}}`}}
      - experiment
      - update
      - --experiment-definition
      - /experiment-definition.yaml
      - --experiment-id
      - '{{`{{workflow.parameters.experiment-id}}`}}'
      - --out
      - /provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
  - name: delete
    inputs:
      parameters:
      - name: provider-image
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /provider-output.yaml
    metadata:
      {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 6 }}
    container:
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      volumeMounts:
      - name: providers-config
        mountPath: /providers-config
      command:
      - /provider
      args:
      - --provider-config
      - /providers-config/{{`{{workflow.parameters.provider-name}}`}}
      - experiment
      - delete
      - --experiment-definition
      - /experiment-definition.yaml
      - --experiment-id
      - '{{`{{workflow.parameters.experiment-id}}`}}'
      - --out
      - /provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-create-experiment
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  ttlStrategy:
    {{- .Values.manager.argo.ttlStrategy | toYaml | nindent 4 }}
  arguments:
    parameters:
    - name: provider-name
    - name: experiment-definition
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: provider
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-experiment-steps
          template: create
        arguments:
          parameters:
          - name: provider-image
            value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-update-experiment
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  ttlStrategy:
    {{- .Values.manager.argo.ttlStrategy | toYaml | nindent 4 }}
  arguments:
    parameters:
    - name: provider-name
    - name: experiment-id
    - name: experiment-definition
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: provider
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-experiment-steps
          template: update
        arguments:
          parameters:
          - name: provider-image
            value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-delete-experiment
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  ttlStrategy:
    {{- .Values.manager.argo.ttlStrategy | toYaml | nindent 4 }}
  arguments:
    parameters:
    - name: provider-name
    - name: experiment-id
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: provider
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-experiment-steps
          template: delete
        arguments:
          parameters:
          - name: provider-image
            value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
