apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-experiment-steps
spec:
  templates:
  - name: create
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: experiment-definition
        path: /tmp/experiment-definition.yaml
        raw:
          data: |
            {{`{{workflow.parameters.experiment-definition}}`}}
      - name: provider-config
        path: /tmp/provider-config.yaml
        raw:
          data: |
            {{`{{workflow.parameters.provider-config}}`}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    metadata:
      {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 6 }}
    container:
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      command:
      - /provider
      args:
      - --provider-config
      - /tmp/provider-config.yaml
      - experiment
      - create
      - --experiment-definition
      - /tmp/experiment-definition.yaml
      - --out
      - /tmp/provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
  - name: update
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: experiment-definition
        path: /tmp/experiment-definition.yaml
        raw:
          data: |
            {{`{{workflow.parameters.experiment-definition}}`}}
      - name: provider-config
        path: /tmp/provider-config.yaml
        raw:
          data: |
            {{`{{workflow.parameters.provider-config}}`}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    metadata:
      {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 6 }}
    container:
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      command:
      - /provider
      args:
      - --provider-config
      - /tmp/provider-config.yaml
      - experiment
      - update
      - --experiment-definition
      - /tmp/experiment-definition.yaml
      - --experiment-id
      - '{{`{{workflow.parameters.experiment-id}}`}}'
      - --out
      - /tmp/provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
  - name: delete
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: provider-config
        path: /tmp/provider-config.yaml
        raw:
          data: |
            {{`{{workflow.parameters.provider-config}}`}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    metadata:
      {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 6 }}
    container:
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      command:
      - /provider
      args:
      - --provider-config
      - /tmp/provider-config.yaml
      - experiment
      - delete
      - --experiment-definition
      - /tmp/experiment-definition.yaml
      - --experiment-id
      - '{{`{{workflow.parameters.experiment-id}}`}}'
      - --out
      - /tmp/provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-create-experiment
spec:
  ttlStrategy:
    {{- .Values.manager.argo.ttlStrategy | toYaml | nindent 4 }}
  arguments:
    parameters:
    - name: experiment-definition
    - name: provider-config
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
          clusterScope: true
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: provider
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-experiment-steps
          template: create
          clusterScope: true
        arguments:
          parameters:
          - name: provider-image
            value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-update-experiment
spec:
  ttlStrategy:
    {{- .Values.manager.argo.ttlStrategy | toYaml | nindent 4 }}
  arguments:
    parameters:
    - name: experiment-definition
    - name: provider-config
    - name: experiment-id
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
          clusterScope: true
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: provider
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-experiment-steps
          template: update
          clusterScope: true
        arguments:
          parameters:
          - name: provider-image
            value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-delete-experiment
spec:
  ttlStrategy:
    {{- .Values.manager.argo.ttlStrategy | toYaml | nindent 4 }}
  arguments:
    parameters:
    - name: provider-config
    - name: experiment-id
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
          clusterScope: true
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: provider
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-experiment-steps
          template: delete
          clusterScope: true
        arguments:
          parameters:
          - name: provider-image
            value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
