apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-pipeline-steps
spec:
  templates:
  - name: compile
    inputs:
      parameters:
      - name: pipeline-image
      artifacts:
      - name: pipeline-definition
        raw:
          data: |
            {{`{{workflow.parameters.pipeline-definition}}`}}
        path: /tmp/pipeline-definition.yaml
    outputs:
      artifacts:
      - name: pipeline
        path: /tmp/pipeline.yaml
    metadata:
      {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 6 }}
    container:
      command:
      - /shared/compile.sh
      image: "{{`{{inputs.parameters.pipeline-image}}`}}"
      name: pipeline
      volumeMounts:
      - mountPath: /shared
        name: shared
      args:
      - --output_file
      - /tmp/pipeline.yaml
      - --pipeline_config
      - /tmp/pipeline-definition.yaml
      {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
    volumes:
    - name: shared
    initContainers:
    - args:
      - /shared
      image: {{ include "kfp-operator.trimmedContainerRegistry" . }}kfp-operator-argo-kfp-compiler:{{ .Chart.AppVersion }}
      mirrorVolumeMounts: true
      name: compile
      {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
  - name: create
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: pipeline
        path: /tmp/pipeline.yaml
      - name: pipeline-definition
        path: /tmp/pipeline-definition.yaml
        raw:
          data: |
            {{`{{workflow.parameters.pipeline-definition}}`}}
      - name: provider-config
        path: /tmp/provider-config.yaml
        raw:
          data: |
            {{`{{workflow.parameters.provider-config}}`}}
    outputs:
      parameters:
        - name: provider-output
          valueFrom:
            path: /tmp/provider-output.yaml
    metadata:
      {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 6 }}
    container:
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      command:
      - /provider
      args:
      - pipeline
      - create
      - --pipeline-definition
      - /tmp/pipeline-definition.yaml
      - --provider-config
      - /tmp/provider-config.yaml
      - --pipeline-file
      - /tmp/pipeline.yaml
      - --out
      - /tmp/provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
  - name: update
    inputs:
      artifacts:
      - name: pipeline
        path: /tmp/pipeline.yaml
      - name: pipeline-definition
        path: /tmp/pipeline-definition.yaml
        raw:
          data: |
            {{`{{workflow.parameters.pipeline-definition}}`}}
      - name: provider-config
        path: /tmp/provider-config.yaml
        raw:
          data: |
            {{`{{workflow.parameters.provider-config}}`}}
      parameters:
      - name: pipeline-id
      - name: provider-image
    outputs:
      parameters:
        - name: provider-output
          valueFrom:
            path: /tmp/provider-output.yaml
    metadata:
      {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 6 }}
    container:
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      command:
      - /provider
      args:
      - pipeline
      - update
      - --pipeline-definition
      - /tmp/pipeline-definition.yaml
      - --provider-config
      - /tmp/provider-config.yaml
      - --pipeline-id
      - '{{`{{inputs.parameters.pipeline-id}}`}}'
      - --pipeline-file
      - /tmp/pipeline.yaml
      - --out
      - /tmp/provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
  - name: delete
    inputs:
      parameters:
      - name: provider-image
      artifacts:
      - name: provider-config
        path: /tmp/provider-config.yaml
        raw:
          data: |
            {{`{{workflow.parameters.provider-config}}`}}
    outputs:
      parameters:
        - name: provider-output
          valueFrom:
            path: /tmp/provider-output.yaml
    metadata:
      {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 6 }}
    container:
      command:
      - /provider
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      args:
      - pipeline
      - delete
      - --pipeline-definition
      - /tmp/pipeline-definition.yaml
      - --provider-config
      - /tmp/provider-config.yaml
      - --pipeline-id
      - '{{`{{workflow.parameters.pipeline-id}}`}}'
      - --out
      - /tmp/provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-create-pipeline
spec:
  arguments:
    parameters:
      - name: pipeline-definition
      - name: provider-config
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
    - name: main
      outputs:
        parameters:
          - name: provider-output
            valueFrom:
              parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
      steps:
      - - name: select-provider-image
          templateRef:
            name: {{ include "kfp-operator.fullname" . }}-common-steps
            template: select-provider-image
            clusterScope: true
      - - name: select-pipeline-image
          templateRef:
            name: {{ include "kfp-operator.fullname" . }}-common-steps
            template: select-pipeline-image
            clusterScope: true
      - - name: compile
          arguments:
            parameters:
            - name: pipeline-image
              value: '{{`{{steps.select-pipeline-image.outputs.result}}`}}'
          templateRef:
            name: {{ include "kfp-operator.fullname" . }}-pipeline-steps
            template: compile
            clusterScope: true
      - - name: provider
          arguments:
            artifacts:
            - from: '{{`{{steps.compile.outputs.artifacts.pipeline}}`}}'
              name: pipeline
            parameters:
            - name: provider-image
              value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
          templateRef:
            name: {{ include "kfp-operator.fullname" . }}-pipeline-steps
            template: create
            clusterScope: true
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-update-pipeline
spec:
  arguments:
    parameters:
      - name: pipeline-definition
      - name: provider-config
      - name: pipeline-id
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
    - name: main
      outputs:
        parameters:
          - name: provider-output
            valueFrom:
              parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
      steps:
      - - name: select-provider-image
          templateRef:
            name: {{ include "kfp-operator.fullname" . }}-common-steps
            template: select-provider-image
            clusterScope: true
      - - name: select-pipeline-image
          templateRef:
            name: {{ include "kfp-operator.fullname" . }}-common-steps
            template: select-pipeline-image
            clusterScope: true
      - - name: compile
          arguments:
            parameters:
            - name: pipeline-image
              value: '{{`{{steps.select-pipeline-image.outputs.result}}`}}'
          templateRef:
            name: {{ include "kfp-operator.fullname" . }}-pipeline-steps
            template: compile
            clusterScope: true
      - - name: provider
          arguments:
            artifacts:
            - from: '{{`{{steps.compile.outputs.artifacts.pipeline}}`}}'
              name: pipeline
            parameters:
            - name: pipeline-id
              value: '{{`{{workflow.parameters.pipeline-id}}`}}'
            - name: provider-image
              value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
          templateRef:
            name: {{ include "kfp-operator.fullname" . }}-pipeline-steps
            template: update
            clusterScope: true
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-delete-pipeline
spec:
  arguments:
    parameters:
    - name: provider-config
    - name: pipeline-id
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    outputs:
      parameters:
          - name: provider-output
            valueFrom:
              parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-image
          clusterScope: true
    - - name: provider
        arguments:
          parameters:
          - name: provider-image
            value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-pipeline-steps
          template: delete
          clusterScope: true
