{{- if .Values.manager.argo.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.manager.argo.serviceAccount.name }}
  namespace: {{ include "kfp-operator.argoNamespace" . }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kfp-operator.fullname" . }}-workflow-executor
  namespace: {{ include "kfp-operator.argoNamespace" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kfp-operator.fullname" . }}-workflow-executor
  namespace: {{ include "kfp-operator.argoNamespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kfp-operator.fullname" . }}-workflow-executor
subjects:
  - kind: ServiceAccount
    name: {{ .Values.manager.argo.serviceAccount.name }}
    namespace: {{ include "kfp-operator.argoNamespace" . }}
{{- range $providerName, $providerBlock := .Values.providers }}
  - kind: ServiceAccount
    name: {{ $providerBlock.configuration.serviceAccount }}
    namespace: {{ include "kfp-operator.argoNamespace" $ }}
{{- end -}}
