apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-simple-workflow-steps
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  templates:
  - name: create
    inputs:
      parameters:
      - name: provider-image
      - name: provider-sa
      artifacts:
      - name: resource-definition
        path: /resource-definition.yaml
        raw:
          data: |
            {{`{{workflow.parameters.resource-definition}}`}}
      - name: provider-config
        path: /provider-config.yaml
        raw:
          data: |
            {{`{{workflow.parameters.provider-config}}`}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    podSpecPatch: '{"serviceAccountName": "{{`{{inputs.parameters.provider-sa}}`}}"}'
    metadata:
      {{- .Values.manager.argo.metadata | toYaml | nindent 6 }}
    activeDeadlineSeconds: {{ .Values.manager.argo.stepTimeoutSeconds.default }}
    container:
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      command:
      - /provider
      args:
      - --provider-config
      - /provider-config
      - '{{`{{workflow.parameters.resource-kind}}`}}'
      - create
      - --{{`{{workflow.parameters.resource-kind}}`}}-definition
      - /resource-definition.yaml
      - --out
      - /tmp/provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
  - name: update
    inputs:
      parameters:
      - name: provider-image
      - name: provider-sa
      artifacts:
      - name: resource-definition
        path: /resource-definition.yaml
        raw:
          data: |
            {{`{{workflow.parameters.resource-definition}}`}}
      - name: provider-config
        path: /provider-config.yaml
        raw:
          data: |
            {{`{{workflow.parameters.provider-config}}`}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          path: /tmp/provider-output.yaml
    podSpecPatch: '{"serviceAccountName": "{{`{{inputs.parameters.provider-sa}}`}}"}'
    metadata:
      {{- .Values.manager.argo.metadata | toYaml | nindent 6 }}
    activeDeadlineSeconds: {{ .Values.manager.argo.stepTimeoutSeconds.default }}
    container:
      image: "{{`{{inputs.parameters.provider-image}}`}}"
      command:
      - /provider
      args:
      - --provider-config
      - /providers-config
      - '{{`{{workflow.parameters.resource-kind}}`}}'
      - update
      - --{{`{{workflow.parameters.resource-kind}}`}}-definition
      - /resource-definition.yaml
      - --{{`{{workflow.parameters.resource-kind}}`}}-id
      - '{{`{{workflow.parameters.resource-id}}`}}'
      - --out
      - /tmp/provider-output.yaml
    {{- include "kfp-operator.notEmptyYaml" .Values.manager.argo.containerDefaults | nindent 6 }}
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-create-simple
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  ttlStrategy:
    {{- .Values.manager.argo.ttlStrategy | toYaml | nindent 4 }}
  arguments:
    parameters:
    - name: provider-name
    - name: provider-config
    - name: resource-kind
    - name: resource-definition
  entrypoint: main
  serviceAccountName: {{ .Values.manager.argo.serviceAccount.name }}
  templates:
  - name: main
    inputs:
      artifacts:
      - name: provider-config
        path: /provider-config.yaml
        raw:
          data: |
            {{`{{workflow.parameters.provider-config}}`}}
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: select-provider-sa
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: serviceAccount
    - - name: provider
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-simple-workflow-steps
          template: create
        arguments:
          parameters:
          - name: provider-image
            value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
          - name: provider-sa
            value: '{{`{{steps.select-provider-sa.outputs.result}}`}}'
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-update-simple
  namespace: {{ include "kfp-operator.argoNamespace" . }}
spec:
  arguments:
    parameters:
    - name: provider-name
    - name: provider-config
    - name: resource-kind
    - name: resource-id
    - name: resource-definition
  entrypoint: main
  serviceAccountName: {{ .Values.manager.argo.serviceAccount.name }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: provider-output
        valueFrom:
          parameter: '{{`{{steps.provider.outputs.parameters.provider-output}}`}}'
    steps:
    - - name: select-provider-image
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: image
    - - name: select-provider-sa
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-common-steps
          template: select-provider-parameter
        arguments:
          parameters:
          - name: parameter
            value: serviceAccount
    - - name: provider
        templateRef:
          name: {{ include "kfp-operator.fullname" . }}-simple-workflow-steps
          template: update
        arguments:
          parameters:
          - name: provider-image
            value: '{{`{{steps.select-provider-image.outputs.result}}`}}'
          - name: provider-sa
            value: '{{`{{steps.select-provider-sa.outputs.result}}`}}'
