- op: replace
  path: /webhooks/0/clientConfig/service/namespace
  value: kfp-operator-system
- op: replace
  path: /webhooks/1/clientConfig/service/namespace
  value: kfp-operator-system
- op: replace
  path: /webhooks/2/clientConfig/service/namespace
  value: kfp-operator-system
