apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-completion-event-trigger
  namespace: kfp-operator-system
  labels:
    app: run-completion-event-trigger
spec:
  selector:
    matchLabels:
      app: run-completion-event-trigger
  replicas: 1
  template:
    metadata:
      labels:
        app: run-completion-event-trigger
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: run-completion-event-trigger
        image: kfp-operator-run-completion-event-trigger:latest
        ports:
        - name: grpc-server
          containerPort: 50051
        volumeMounts:
          - name: config
            subPath: config.yaml
            mountPath: /etc/run-completion-event-trigger/config.yaml
      volumes:
        - name: config
          configMap:
            name: run-completion-event-trigger

