apiVersion: v1
kind: Service
metadata:
  name: run-completion-event-trigger
  namespace: kfp-operator-system
spec:
  selector:
    app: run-completion-event-trigger
  ports:
  - protocol: TCP
    port: 50051
    targetPort: grpc-server
