services:
  pubsub:
    container_name: pubsub
    image: google/cloud-sdk:emulators
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
    - "8085:8085"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/" ]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 1s
