apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kfp-operator.fullname" . }}-nats-event-trigger-config
  namespace: {{ .Values.namespace.name }}
data:
  nats_event_trigger_config.yaml: 
    subject: events 
    url: blah.blah.blahblahblah:port
