# Default values for kfp-operator-crds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  name: "kfp-operator-system"

manager:
  monitoring:
    create: false
    rbacSecured: false
  multiversion:
    enabled: false
    storedVersion: v1beta1
  rbac:
    create: true
