apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-event-trigger
  namespace: kfp-operator-system
data:
  config.yaml: |
    natsConfig:
      subject: events
      serverConfig:
        host: https://localhost
        port: 4222
    serverConfig:
      host: localhost
      port: 50051
