apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native: {}
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: run-completion
spec:
  generic:
    run-completion:
      insecure: true
      url: "kfp-operator-run-completion-eventsource-server.kfp-operator-system.svc:8080"
      config: |-
        kfpNamespace: kubeflow-pipelines
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: penguin-pipeline-model-update
spec:
  template:
    serviceAccountName: events-sa
  dependencies:
    - name: run-completion
      eventSourceName: run-completion
      eventName: run-completion
      filters:
        data:
          - path: body
            template: '{{ ((b64dec .Input) | mustFromJson).status }}'
            type: string
            comparator: "="
            value:
              - "succeeded"
          - path: body
            template: '{{ ((b64dec .Input) | mustFromJson).pipelineName }}'
            type: string
            comparator: "="
            value:
              - "penguin-pipeline"
  triggers:
    - template:
        k8s:
          operation: update
          source:
            resource:
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: serving-config
              data:
                servingModel: ""
      parameters:
        - src:
            dependencyName: run-completion
            dataKey: '{{ (index ((b64dec .Input) | mustFromJson).servingModelArtifacts 0).location }}'
          dest: data.servingModel
