include ../../version.mk

IMG := kfp-operator-argo-kfp-sdk

all: build

##@ Development

test: build
	@echo Nothing to test.

##@ Build

build:
	@echo Nothing to build.

##@ Containers

include ../../docker-targets.mk
