apiVersion: v1
kind: Service
metadata:
  name: {{ include "kfp-operator.fullname" . }}-nats-event-trigger
  namespace: kfp-operator-system
spec:
  selector:
    app: nats-event-trigger
  ports:
  - protocol: TCP
    port: {{ .Values.natsEventTrigger.server.port }}
    targetPort: grpc-server
