// Code generated by "stringer -type sendEventsMetricAttribute"; DO NOT EDIT.

package sinks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[RecoverableFailure-1]
	_ = x[UnrecoverableFailure-2]
	_ = x[Discarded-3]
}

const _sendEventsMetricAttribute_name = "SuccessRecoverableFailureUnrecoverableFailureDiscarded"

var _sendEventsMetricAttribute_index = [...]uint8{0, 7, 25, 45, 54}

func (i sendEventsMetricAttribute) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_sendEventsMetricAttribute_index)-1 {
		return "sendEventsMetricAttribute(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sendEventsMetricAttribute_name[_sendEventsMetricAttribute_index[idx]:_sendEventsMetricAttribute_index[idx+1]]
}
