{{- if .Values.manager.monitoring.create -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: {{ include "kfp-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    {{ if .Values.manager.monitoring.rbacSecured -}}
    - name: https
      port: 8443
      targetPort: https
    {{- else -}}
    - name: http
      port: 8080
      targetPort: http
    {{- end }}
  selector:
    control-plane: controller-manager
{{- end -}}
