{{- if and .Values.manager.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "kfp-operator.fullname" . }}-manager-role
rules:
- apiGroups:
    - argoproj.io
  resources:
    - workflows
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - pipelines.kubeflow.org
  resources:
    - pipelines
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - pipelines.kubeflow.org
  resources:
    - pipelines/finalizers
  verbs:
    - update
- apiGroups:
    - pipelines.kubeflow.org
  resources:
    - pipelines/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - pipelines.kubeflow.org
  resources:
    - runconfigurations
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - pipelines.kubeflow.org
  resources:
    - runconfigurations/finalizers
  verbs:
    - update
- apiGroups:
    - pipelines.kubeflow.org
  resources:
    - runconfigurations/status
  verbs:
    - get
    - patch
    - update
{{- end -}}
