{{- if .Values.rbac.create -}}
# permissions for end users to edit runconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kfp-operator.fullname" . }}-runconfiguration-editor-role
rules:
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - runconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - runconfigurations/status
  verbs:
  - get
{{- end -}}
