{{- range $providerName, $providerBlock := .Values.providers }}
{{- if $providerBlock.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $providerBlock.serviceAccount.name }}
  namespace: {{ include "kfp-operator.argoNamespace" $ }}
{{- if $providerBlock.serviceAccount.metadata }}
  {{ $providerBlock.serviceAccount.metadata | toYaml | nindent 2 }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kfp-operator.fullname" $ }}-{{ $providerName }}-runconfiguration-viewer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kfp-operator.fullname" $ }}-runconfiguration-viewer-role
subjects:
  - kind: ServiceAccount
    name: {{ $providerBlock.serviceAccount.name }}
    namespace: {{ include "kfp-operator.argoNamespace" $ }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kfp-operator.fullname" $ }}-{{ $providerName }}-run-viewer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kfp-operator.fullname" $ }}-run-viewer-role
subjects:
  - kind: ServiceAccount
    name: {{ $providerBlock.serviceAccount.name }}
    namespace: {{ include "kfp-operator.argoNamespace" $ }}
---
{{- end }}
{{- if .Values.providers }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kfp-operator.fullname" . }}-provider-workflow-executor
  namespace: {{ include "kfp-operator.argoNamespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kfp-operator.fullname" . }}-workflow-executor
subjects:
{{- range $providerName, $providerBlock := .Values.providers }}
  - kind: ServiceAccount
    name: {{ $providerBlock.serviceAccount.name }}
    namespace: {{ include "kfp-operator.argoNamespace" $ }}
{{- end -}}
{{- end -}}
