baseURL = 'http://example.org/'
languageCode = 'en-gb'
title = 'Kubeflow Pipelines'
theme = "github.com/google/docsy"

[module]

[module.hugoVersion]
extended = true

[[module.imports]]
path = 'github.com/google/docsy'
disable=false
[[module.imports]]
path = "github.com/google/docsy/dependencies"
disable = false    
