{{- if and .Values.eventsourceServer.create .Values.manager.rbac.create -}}
{{- if (include "kfp-operator.providerTypeExists" (merge (dict "ProviderType" "kfp") . )) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "kfp-operator.fullname" . }}-kfp-eventsource-server-role
rules:
- apiGroups:
    - argoproj.io
  resources:
    - workflows
  verbs:
    - get
    - list
    - patch
    - update
    - watch
{{- end -}}

{{- range $providerName, $providerBlock := .Values.providers -}}
{{- if eq $providerBlock.type "kfp" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kfp-operator.fullname" $ }}-{{ $providerName }}-eventsource-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kfp-operator.fullname" $ }}-kfp-eventsource-server-role
subjects:
- kind: ServiceAccount
  name: {{ $providerBlock.configuration.serviceAccount }}
  namespace: {{ include "kfp-operator.argoNamespace" $ }}
{{- end -}}
{{- end -}}
{{- end -}}
