services:
  nats-event-triggers:
    image: kfp-operator-nats-event-trigger
    ports:
      - 50051:50051
    environment:
      NATSCONFIG_SERVERCONFIG_HOST: nats
      SERVERCONFIG_HOST: 0.0.0.0
    depends_on:
      - nats

  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
