baseURL = 'https://sky-uk.github.io/kfp-operator'
languageCode = 'en-gb'
title = 'KFP-Operator'
theme = "github.com/google/docsy"
publishDir = '../docs'

[menu]
  [[menu.main]]
    name = "Documentation"
    weight = -101
    pre = "<i class='fas fa-book pr-2'></i>"
    url = "/docs/"
  [[menu.main]]
    name = "GitHub"
    weight = -99
    pre = "<i class='fab fa-github pr-2'></i>"
    url = "https://github.com/sky-uk/kfp-operator"

[module]
    [module.hugoVersion]
        extended = true
    [[module.imports]]
        path = 'github.com/google/docsy'
        disable=false
    [[module.imports]]
        path = "github.com/google/docsy/dependencies"
        disable = false

[params]
  github_repo = "https://github.com/sky-uk/kfp-operator"
  github_subdir = "docs-gen"
  github_branch = "master"
  github_project_repo = "https://github.com/sky-uk/kfp-operator"
