baseURL = 'https://sky-uk.github.io/kfp-operator'
languageCode = 'en-gb'
title = 'KFP-Operator'
theme = "github.com/google/docsy"
publishDir = '../docs'
canonifyURLs = false

[menu]
  [[menu.main]]
    name = "Documentation"
    weight = -101
    url = "/versions/v0.6.0"
    pre = "<i class='fa-solid fa-book'></i>"
  [[menu.main]]
    name = "Discuss"
    weight = -100
    pre = "<i class='fas fa-comments'></i>"
    url = "https://github.com/sky-uk/kfp-operator/discussions"
  [[menu.main]]
    name = "GitHub"
    weight = -99
    pre = "<i class='fab fa-github pr-2'></i>"
    url = "https://github.com/sky-uk/kfp-operator"

[module]
    [module.hugoVersion]
        extended = true
    [[module.imports]]
        path = 'github.com/google/docsy'
        disable=false
    [[module.imports]]
        path = "github.com/google/docsy/dependencies"
        disable = false

[security.exec]
  osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|HOME|ASDF_DIR)$']

[markup.goldmark.renderer]
unsafe = true

[params]
  description = "Kubernetes operator to manage ML pipelines on Kubeflow"
  github_repo = "https://github.com/sky-uk/kfp-operator"
  github_subdir = "docs-gen"
  github_branch = "master"
  github_project_repo = "https://github.com/sky-uk/kfp-operator"
  subpath = "/kfp-operator"
  version_menu = "Version"
  latest_stable_version = "v0.6.0"

[params.ui]
navbar_logo = false
showLightDarkModeMenu = true

[[params.versions]]
version = "master"
url = "/kfp-operator/docs/"

[[params.versions]]
version = "v0.6.0"
url = "/kfp-operator/archive/v0.6.0/"

[[params.versions]]
version = "master"
url = "/kfp-operator/docs/"

[[params.versions]]
version = "v0.6.0"
url = "/kfp-operator/versions/v0.6.0"
