baseURL = 'https://sky-uk.github.io/kfp-operator'
languageCode = 'en-gb'
title = 'KFP-Operator'
theme = "github.com/google/docsy"
publishDir = '../docs'
canonifyURLs = false

[menu]
  [[menu.main]]
    name = "Discuss"
    weight = -100
    pre = "<i class='fas fa-comments'></i>"
    url = "https://github.com/sky-uk/kfp-operator/discussions"
  [[menu.main]]
    name = "GitHub"
    weight = -99
    pre = "<i class='fab fa-github pr-2'></i>"
    url = "https://github.com/sky-uk/kfp-operator"

[module]
    [module.hugoVersion]
        extended = true
    [[module.imports]]
        path = 'github.com/google/docsy'
        disable=false
    [[module.imports]]
        path = "github.com/google/docsy/dependencies"
        disable = false

[params]
  description = "Kubernetes operator to manage ML pipelines on Kubeflow"
  github_repo = "https://github.com/sky-uk/kfp-operator"
  github_subdir = "docs-gen"
  github_branch = "master"
  github_project_repo = "https://github.com/sky-uk/kfp-operator"
  subpath = "/kfp-operator"
  version_menu = "Version"


[params.ui]
navbar_logo = false
showLightDarkModeMenu = true
ul_show = 5
ul_min_show = 5
ul_show_children = 5
ul_min_show_children = 5
ul_show_grandchildren = 5
ul_min_show_grandchildren = 5

sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_menu_collapsible = true


[[params.versions]]
version = "master"
url = "https://github.com/sky-uk/kfp-operator/kfp-operator/docs/master"

[[params.versions]]
version = "v0.6.0"
url = "https://github.com/sky-uk/kfp-operator/kfp-operator/docs/v0.6.0"

[security.exec]
  osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|HOME|ASDF_DIR)$']

[markup.goldmark.renderer]
unsafe = true

