{{- $providerName := .Values.provider.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kfp-operator-provider.resource-prefix" . }}-{{ $providerName }}-config
  namespace: {{ include "kfp-operator-provider.namespace" . }}
data:
  {{ $providerName }}: |
    name: {{ $providerName }}
    image: {{ include "kfp-operator-provider.image" $ }}
    executionMode: {{ .Values.provider.executionMode }}
    serviceAccount: {{ .Values.provider.serviceAccount.name }}
    {{- if not (empty .Values.provider.configuration) -}}
    {{- .Values.provider.configuration | toYaml | nindent 4 }}
    {{- end }}

{{- range $providerName, $providerBlock := .Values.providers }}
---
apiVersion: pipelines.kubeflow.org/v1alpha5
kind: Provider
metadata:
  name: {{ $providerName }}
  namespace: {{ default $.Values.namespace.name $providerBlock.namespace }}
spec:
  image: {{ include "kfp-operator-provider.image" $ }}
  executionMode: {{ .Values.provider.executionMode }}
  serviceAccount: {{ .Values.provider.serviceAccount.name }}
  defaultBeamArgs:
  {{- .Values.provider.configuration.defaultBeamArgs | toYaml | nindent 2 }}
  pipelineRootStorage: {{ .Values.provider.configuration.pipelineRootStorage }}
  parameters:
    {{- $providerParams := omit .Values.provider.configuration "defaultBeamArgs" "pipelineRootStorage" -}}
    {{- $providerParams | toYaml | nindent 4 }}
{{- end -}}
