{{- $providerName := .Values.provider.name }}
apiVersion: pipelines.kubeflow.org/v1alpha6
kind: Provider
metadata:
  name: {{ $providerName }}
  namespace: {{ include "kfp-operator-provider.namespace" . }}
spec:
  cliImage: {{ include "kfp-operator-provider.cliImage" $ }}
  executionMode: {{ .Values.provider.executionMode }}
  serviceAccount: {{ .Values.provider.serviceAccount.name }}
  defaultBeamArgs:
    {{- .Values.provider.configuration.defaultBeamArgs | toYaml | nindent 4 }}
  pipelineRootStorage: {{ .Values.provider.configuration.pipelineRootStorage }}
  parameters:
    {{- $providerParams := omit .Values.provider.configuration "defaultBeamArgs" "pipelineRootStorage" -}}
    {{- $providerParams | toYaml | nindent 4 }}
